project:
  type: website

website:
  title: "Génesis Website Hub"
  page-navigation: true
  navbar:
    left:
      - about.qmd
      - href: ../gg_blog/index.qmd
        text: GG Blog

format:
  html:
    theme: light
    css: styles.css
    toc: true
    smooth-scroll: true
